<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Income Report - {{ $school->school_name }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 0;
            text-transform: uppercase;
            color: #2563eb;
        }

        .header p {
            margin: 5px 0;
            font-size: 10px;
            color: #666;
        }

        .report-info {
            margin-bottom: 20px;
            width: 100%;
        }

        .report-info td {
            font-size: 11px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #f8fafc;
            color: #64748b;
            text-align: left;
            padding: 10px 5px;
            border: 1px solid #e2e8f0;
            text-transform: uppercase;
            font-size: 10px;
        }

        td {
            padding: 8px 5px;
            border: 1px solid #e2e8f0;
            vertical-align: top;
        }

        .footer {
            margin-top: 50px;
            width: 100%;
        }

        .signature {
            border-top: 1px solid #333;
            width: 200px;
            text-align: center;
            float: right;
            padding-top: 5px;
            font-weight: bold;
        }

        .total-row {
            background-color: #f1f5f9;
            font-weight: bold;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }
    </style>
</head>

<body>

    <div class="header">
        <h2>{{ $school->school_name }}</h2>
        <p>{{ $school->address ?? 'School Income Management System' }}</p>
        {{-- Corrected $school->mobile_number to $school->mobile --}}
        <p>Mobile: {{ $school->mobile ?? '' }} | Email: {{ $school->email ?? '' }}</p>
    </div>

    <table class="report-info">
        <tr>
            <td><strong>REPORT:</strong> INCOME STATEMENT</td>
            <td class="text-right"><strong>PRINT DATE:</strong> {{ $date }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th width="30">SL</th>
                <th width="80">Date</th>
                <th>Source</th>
                <th>Payer Name</th>
                <th>Address</th>
                <th width="90">Mobile</th>
                <th width="80" class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @php $total = 0; @endphp
            @foreach ($incomes as $index => $income)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ date('d-m-Y', strtotime($income->date)) }}</td>
                    <td>{{ $income->income_source }}</td>
                    <td><strong>{{ $income->name }}</strong></td>
                    <td>{{ $income->address ?? 'N/A' }}</td>
                    <td>{{ $income->mobile }}</td>
                    <td class="text-right">{{ number_format($income->amount, 2) }} ৳</td>
                </tr>
                @php $total += $income->amount; @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="6" class="text-right">GRAND TOTAL:</td>
                <td class="text-right">{{ number_format($total, 2) }} ৳</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <div class="signature">
            Authorized Signature
        </div>
        <p style="font-size: 8px; color: #999;">Generated by {{ config('app.name') }} on
            {{ now()->format('d-m-Y H:i:s') }}</p>
    </div>

</body>

</html>
